# Generated by Django 5.1.4 on 2024-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinformation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='car_pictures/'),
        ),
        migrations.AlterField(
            model_name='carinformation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carinformation',
            name='car_owner',
            field=models.CharField(max_length=100),
        ),
    ]
